name: fb-random-post-from-feed-photo
on:
  push:
    branches: master
  schedule:
    - cron: '0 19 * * *'
  watch:
    types: [started]
jobs:
  fb-random-post-from-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: sudo pip install -r requirements.txt
      - name: Update
        uses: ./photoPost
        env:
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FEED_URL: ${{ secrets.FEED_URL }}
